# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/ip/input_image/input_image.xci
# IP: The module: 'input_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/ip/input_image/input_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_image'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/ip/input_image/input_image.xci
# IP: The module: 'input_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/ip/input_image/input_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
