# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/.Xil/Vivado-16908-THAMEERA-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image}
    {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/ip/output_image}
    {d:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/ip/input_image}
  } C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_vhdl -lib xil_defaultlib {
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/.Xil/Vivado-16908-THAMEERA-PC/realtime/input_image_stub.vhdl}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/.Xil/Vivado-16908-THAMEERA-PC/realtime/padded_image_stub.vhdl}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/.Xil/Vivado-16908-THAMEERA-PC/realtime/output_image_stub.vhdl}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/new/UART.vhd}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/new/UART_comms.vhd}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/new/baud_generator.vhd}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/new/convolve.vhd}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/new/fsm.vhd}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/new/padding.vhd}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/new/uart_tx.vhd}
      {D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/edge_detection.srcs/sources_1/new/main.vhd}
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top main
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/thameera/ACA Folder/sem8/hdl/project/HDL_Project/.Xil/Vivado-16908-THAMEERA-PC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
