# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/code/HDL/config.xdc

# IP: ip/input_image/input_image.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==input_image || ORIG_REF_NAME==input_image} -quiet] -quiet
