# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/code/hdl2/HDL_Project/edge_detection.cache/wt [current_project]
set_property parent.project_path D:/code/hdl2/HDL_Project/edge_detection.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo d:/code/hdl2/HDL_Project/edge_detection.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/image_ram_init_data.coe
add_files D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image/padded_ram.coe
add_files D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image/padded_ram1.coe
add_files D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/input_image/sd.coe
read_vhdl -library xil_defaultlib {
  D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/new/UART.vhd
  D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/new/convolve.vhd
  D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/new/fsm.vhd
  D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/new/padding.vhd
  D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/new/uartComms.vhd
  D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/new/main.vhd
}
read_ip -quiet D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/input_image/input_image.xci
set_property used_in_implementation false [get_files -all d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/input_image/input_image_ooc.xdc]

read_ip -quiet D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image/padded_image.xci
set_property used_in_implementation false [get_files -all d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image/padded_image_ooc.xdc]

read_ip -quiet D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/output_image/output_image.xci
set_property used_in_implementation false [get_files -all d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/output_image/output_image_ooc.xdc]

read_ip -quiet D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xci
set_property used_in_implementation false [get_files -all d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/code/HDL/config.xdc
set_property used_in_implementation false [get_files D:/code/HDL/config.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
