# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xci
# IP: The module: 'axi_uartlite_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xci
# IP: The module: 'axi_uartlite_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/code/hdl2/HDL_Project/edge_detection.srcs/sources_1/ip/axi_uartlite_0/axi_uartlite_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
