# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/code/HDL/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image/padded_image.xci
# IP: The module: 'padded_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/HDL/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image/padded_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'padded_image'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/code/HDL/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image/padded_image.xci
# IP: The module: 'padded_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/HDL/HDL_Project/edge_detection.srcs/sources_1/ip/padded_image/padded_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'padded_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
